[package]
name = "deadeye_strat_backtest"
version = "0.1.0"
edition = "2024"

[dependencies]
deadeye-sdk = "0.1.4"
tokio = { version = "1.43", features = ["macros", "rt-multi-thread"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[profile.release]
opt-level = 3
lto = "thin"
